import fs from 'node:fs'
import path from 'node:path'
import react from '@vitejs/plugin-react'
import { defineConfig, type Plugin } from 'vite'
import pkg from './package.json'

/**
 * Generates a production service worker with a precise precache list built
 * from Vite's actual output filenames (which include content hashes).
 * Runs after the bundle is written so it can overwrite the public/sw.js copy.
 */
function swPlugin(): Plugin {
  let outDir = 'dist'
  const assets: string[] = []

  return {
    name: 'sw-generator',
    apply: 'build',

    configResolved(config) {
      outDir = config.build.outDir
    },

    generateBundle(_opts, bundle) {
      for (const name of Object.keys(bundle)) {
        if (!name.endsWith('.map')) assets.push(`/${name}`)
      }
    },

    closeBundle() {
      const precache = JSON.stringify(
        [
          '/index.html',
          '/manifest.json',
          '/icon-192.png',
          '/icon-512.png',
          '/icon-maskable-512.png',
          ...assets,
        ],
        null, 2,
      )

      const sw = `// Auto-generated by swPlugin — do not edit.
// Rebuilt on every production deploy; includes all content-hashed asset URLs.
const CACHE = 'nid-v${Date.now()}';
const PRECACHE = ${precache};

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => c.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE).map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  // Navigation: serve fresh page, fall back to cached index.html offline
  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request).catch(() => caches.match('/index.html'))
    );
    return;
  }
  // Assets are content-hashed — cache-first is safe
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(res => {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
        return res;
      });
    })
  );
});
`
      fs.writeFileSync(path.resolve(outDir, 'sw.js'), sw)
      console.log('[sw-generator] wrote dist/sw.js with ' + assets.length + ' precached assets')
    },
  }
}

export default defineConfig({
  plugins: [react(), swPlugin()],
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
    __BUILD_DATE__: JSON.stringify(
      new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    ),
  },
})
