// Daily encouragement phrases collected from various AIs.
//
// Two pools:
//   before — shown when today has no logged entries yet ("let's do this")
//   after  — shown once today has at least one exercise logged ("good job")
//
// author === null  → the AI's own words; rendered as a clean message, no attribution.
// author === string → a genuine quote; rendered with "— Author".
//
// To add a batch from another AI, just append its objects to these arrays.
// Source AI is intentionally NOT stored — only real quotes show an author.
// Pools are deduped by phrase text (case/punctuation-insensitive).

export interface Phrase {
  text: string
  kind: 'hype' | 'wise'
  author: string | null
}

export const BEFORE: Phrase[] = [
  // --- Grok ---
  { text: 'Let\'s go — today is YOURS to take.', kind: 'hype', author: null },
  { text: 'You vs you. Let\'s win this round.', kind: 'hype', author: null },
  { text: 'Time to move. I\'m right here with you.', kind: 'hype', author: null },
  { text: 'Get after it. Your future self is watching.', kind: 'hype', author: null },
  { text: 'We got this. One rep at a time.', kind: 'hype', author: null },
  { text: 'Show up strong. The energy is waiting.', kind: 'hype', author: null },
  { text: 'Unlock that power. Let\'s build something.', kind: 'hype', author: null },
  { text: 'You\'re built for this. Go prove it.', kind: 'hype', author: null },
  { text: 'Heart on fire. Let\'s make today count.', kind: 'hype', author: null },
  { text: 'Step up. The couch can wait.', kind: 'hype', author: null },
  { text: 'It is not the mountain we conquer but ourselves.', kind: 'wise', author: 'Edmund Hillary' },
  { text: 'You miss 100% of the shots you don\'t take.', kind: 'wise', author: 'Wayne Gretzky' },
  { text: 'Small daily improvements create stunning results.', kind: 'wise', author: null },
  { text: 'Showing up is how you outpace yesterday.', kind: 'wise', author: null },
  { text: 'Effort compounds. Trust the quiet work.', kind: 'wise', author: null },
  { text: 'The start is the hardest. Then comes momentum.', kind: 'wise', author: null },
  { text: 'Discipline weighs ounces. Regret weighs tons.', kind: 'wise', author: null },
  { text: 'Every beginning carries its own promise.', kind: 'wise', author: null },
  { text: 'Strength grows the moment you choose to move.', kind: 'wise', author: null },
  { text: 'The body achieves what the mind believes.', kind: 'wise', author: 'Napoleon Hill' },
  // --- ChatGPT ---
  { text: 'Come on, you\'ve got more in the tank than you think.', kind: 'hype', author: null },
  { text: 'Let\'s stack one more win today.', kind: 'hype', author: null },
  { text: 'The hardest rep is opening the door. You\'re here.', kind: 'hype', author: null },
  { text: 'We\'re not chasing perfect. We\'re chasing progress.', kind: 'hype', author: null },
  { text: 'Your future self is already cheering for this session.', kind: 'hype', author: null },
  { text: 'Let\'s make today count. One set at a time.', kind: 'hype', author: null },
  { text: 'You showed up. That\'s how momentum begins.', kind: 'hype', author: null },
  { text: 'The couch had its turn. Your goals are up now.', kind: 'hype', author: null },
  { text: 'You\'ve done hard things before. Let\'s do another.', kind: 'hype', author: null },
  { text: 'Today doesn\'t need magic. It needs you.', kind: 'hype', author: null },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.', kind: 'wise', author: 'Will Durant' },
  { text: 'The journey of a thousand miles begins with one step.', kind: 'wise', author: 'Lao Tzu' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', kind: 'wise', author: 'Robert Collier' },
  { text: 'You do not rise to the level of your goals.', kind: 'wise', author: 'James Clear' },
  { text: 'Discipline is choosing what you want most.', kind: 'wise', author: 'Abraham Lincoln' },
  { text: 'Some days the victory is simply not staying home.', kind: 'wise', author: null },
  { text: 'The person you become is built in ordinary moments.', kind: 'wise', author: null },
  { text: 'Patience is effort stretched across time.', kind: 'wise', author: null },
  { text: 'A small workout still counts as a vote for yourself.', kind: 'wise', author: null },
  { text: 'Showing up changes you, even when it feels invisible.', kind: 'wise', author: null },
  // --- Claude ---
  { text: 'Let\'s go. Your future self is already cheering.', kind: 'hype', author: null },
  { text: 'You showed up. That\'s already half the fight.', kind: 'hype', author: null },
  { text: 'I believe in this session before you even start.', kind: 'hype', author: null },
  { text: 'The weights are waiting. Go say hello.', kind: 'hype', author: null },
  { text: 'We do this today so tomorrow feels lighter.', kind: 'hype', author: null },
  { text: 'Every rep you\'re about to do is a vote for who you\'re becoming.', kind: 'hype', author: null },
  { text: 'Don\'t think. Lace up. The body knows what to do.', kind: 'hype', author: null },
  { text: 'Someone else is resting. You\'re not someone else.', kind: 'hype', author: null },
  { text: 'The only workout you\'ll regret is the one you skip.', kind: 'hype', author: null },
  { text: 'Effort costs nothing but time. You have the time.', kind: 'hype', author: null },
  { text: 'Suffer now and live the rest of your life as a champion.', kind: 'wise', author: 'Muhammad Ali' },
  { text: 'The fight is won far from witnesses, in the gym and on the road.', kind: 'wise', author: 'Muhammad Ali' },
  { text: 'I am building a fire. Every day I train, I add more fuel.', kind: 'wise', author: 'Mia Hamm' },
  { text: 'We are what we repeatedly do. Excellence is not an act, but a habit.', kind: 'wise', author: 'Will Durant' },
  { text: 'Showing up on the hard days is the whole practice.', kind: 'wise', author: null },
  { text: 'The body is reluctant before. Grateful after. Trust the after.', kind: 'wise', author: null },
  { text: 'Discipline is just deciding what you care about most.', kind: 'wise', author: null },
  { text: 'Momentum doesn\'t find you sitting still. You find it moving.', kind: 'wise', author: null },
  { text: 'The session doesn\'t have to be perfect. It just has to happen.', kind: 'wise', author: null },
  { text: 'Small and consistent beats brilliant and occasional, every time.', kind: 'wise', author: null },
  // --- Gemini ---
  { text: 'Tie those laces tight, we have work to do.', kind: 'hype', author: null },
  { text: 'Leave the couch behind and show up for yourself.', kind: 'hype', author: null },
  { text: 'We are not just moving weights, we are building you.', kind: 'hype', author: null },
  { text: 'Your future self is waiting for this workout, go.', kind: 'hype', author: null },
  { text: 'One set at a time, let\'s crush every rep today.', kind: 'hype', author: null },
  { text: 'Bring that fire, I am right here with you.', kind: 'hype', author: null },
  { text: 'The hardest part is behind you—just get moving.', kind: 'hype', author: null },
  { text: 'Unlock that potential, today is your day to shine.', kind: 'hype', author: null },
  { text: 'Stop thinking and start feeling the burn.', kind: 'hype', author: null },
  { text: 'We don\'t need motivation, we just need to start.', kind: 'hype', author: null },
  { text: 'Action is the foundational key to all success.', kind: 'wise', author: 'Pablo Picasso' },
  { text: 'Discipline is doing what needs to be done.', kind: 'wise', author: null },
  { text: 'The only bad workout is the one that didn\'t happen.', kind: 'wise', author: null },
  { text: 'It does not matter how slowly you go.', kind: 'wise', author: 'Confucius' },
  { text: 'Growth lives in the moments where you almost quit.', kind: 'wise', author: null },
  { text: 'Well done is better than well said.', kind: 'wise', author: 'Benjamin Franklin' },
  { text: 'Small progress is still progress worth making.', kind: 'wise', author: null },
  { text: 'Fall in love with the process of becoming better.', kind: 'wise', author: null },
  { text: 'Success is the sum of small efforts repeated.', kind: 'wise', author: 'Robert Collier' },
  { text: 'Focus on the path, not the summit.', kind: 'wise', author: null },
  // --- DeepSeek ---
  { text: 'You and this workout — it\'s happening. Let\'s own it.', kind: 'hype', author: null },
  { text: 'The struggle you\'re in today develops the strength you need tomorrow.', kind: 'wise', author: null },
  { text: 'Get up — that fire in you is ready to burn.', kind: 'hype', author: null },
  { text: 'We don\'t rise to the level of our goals; we fall to the level of our systems.', kind: 'wise', author: 'James Clear' },
  { text: 'Your body is ready — trust it and go.', kind: 'hype', author: null },
  { text: 'Do not pray for an easy life; pray for the strength to endure a difficult one.', kind: 'wise', author: 'Bruce Lee' },
  { text: 'Let\'s attack this — you\'re stronger than the excuses.', kind: 'hype', author: null },
  { text: 'Today\'s effort is tomorrow\'s result — go earn it.', kind: 'hype', author: null },
  { text: 'It is never too late to be what you might have been.', kind: 'wise', author: 'George Eliot' },
  { text: 'Get after it — you\'ve got the power to crush this.', kind: 'hype', author: null },
  { text: 'We\'re doing this together — start strong, finish stronger.', kind: 'hype', author: null },
  { text: 'The man who moves a mountain begins by carrying away small stones.', kind: 'wise', author: 'Confucius' },
  { text: 'C\'mon — one rep, one step, one win at a time.', kind: 'hype', author: null },
  { text: 'Don\'t count the days; make the days count.', kind: 'wise', author: 'Muhammad Ali' },
  { text: 'You\'ve got the grit — now go prove it to yourself.', kind: 'hype', author: null },
  { text: 'Strength does not come from physical capacity; it comes from an indomitable will.', kind: 'wise', author: 'Mahatma Gandhi' },
  { text: 'Let\'s get uncomfortable — that\'s where the growth lives.', kind: 'hype', author: null },
  { text: 'The pain you feel today is the strength you\'ll feel tomorrow.', kind: 'wise', author: null },
]

export const AFTER: Phrase[] = [
  // --- Grok ---
  { text: 'Look at you. That\'s how it\'s done.', kind: 'hype', author: null },
  { text: 'Hell yes. You just leveled up.', kind: 'hype', author: null },
  { text: 'Proud of you. That was all heart.', kind: 'hype', author: null },
  { text: 'You showed up and owned it. Legend.', kind: 'hype', author: null },
  { text: 'Strong work. Feel that win in your bones.', kind: 'hype', author: null },
  { text: 'You did the damn thing. Celebrate it.', kind: 'hype', author: null },
  { text: 'That\'s my teammate. Incredible effort.', kind: 'hype', author: null },
  { text: 'You pushed through. Pure fire.', kind: 'hype', author: null },
  { text: 'Mission complete. You\'re unstoppable.', kind: 'hype', author: null },
  { text: 'What a session. You earned every bit of this.', kind: 'hype', author: null },
  { text: 'The pain of today is the strength of tomorrow.', kind: 'wise', author: null },
  { text: 'Progress is hidden in the reps you just finished.', kind: 'wise', author: null },
  { text: 'You didn\'t quit. That\'s the whole game.', kind: 'wise', author: null },
  { text: 'Every workout is a deposit in your future.', kind: 'wise', author: null },
  { text: 'It is the hours you put in when no one sees.', kind: 'wise', author: null },
  { text: 'You are what you repeatedly do.', kind: 'wise', author: 'Aristotle' },
  { text: 'The reward is in the becoming.', kind: 'wise', author: null },
  { text: 'You\'ve grown stronger than you realize.', kind: 'wise', author: null },
  { text: 'Consistency is quiet confidence in action.', kind: 'wise', author: null },
  { text: 'Champions are made in the moments after the decision.', kind: 'wise', author: null },
  // --- ChatGPT ---
  { text: 'There it is. Another promise kept.', kind: 'hype', author: null },
  { text: 'You showed up and did the work. That\'s huge.', kind: 'hype', author: null },
  { text: 'Look at that. You earned today\'s checkmark.', kind: 'hype', author: null },
  { text: 'Nice work. The version of you from yesterday is proud.', kind: 'hype', author: null },
  { text: 'That\'s how momentum is built. One session at a time.', kind: 'hype', author: null },
  { text: 'You didn\'t just think about it. You did it.', kind: 'hype', author: null },
  { text: 'The workout is done. The pride gets to stay.', kind: 'hype', author: null },
  { text: 'Another brick laid. Your wall is getting stronger.', kind: 'hype', author: null },
  { text: 'You gave yourself something worth feeling good about.', kind: 'hype', author: null },
  { text: 'Take a second. That effort mattered.', kind: 'hype', author: null },
  { text: 'It\'s not whether you get knocked down; it\'s whether you get up.', kind: 'wise', author: 'Vince Lombardi' },
  { text: 'The only way to prove that you\'re a good sport is to lose.', kind: 'wise', author: 'Ernie Banks' },
  { text: 'Well done is better than well said.', kind: 'wise', author: 'Benjamin Franklin' },
  { text: 'The strength of the team is each individual member.', kind: 'wise', author: 'Phil Jackson' },
  { text: 'Success is peace of mind from doing your best.', kind: 'wise', author: 'John Wooden' },
  { text: 'Results come and go. The habit remains.', kind: 'wise', author: null },
  { text: 'You cannot bank motivation, but you can build trust.', kind: 'wise', author: null },
  { text: 'Today\'s effort becomes tomorrow\'s confidence.', kind: 'wise', author: null },
  { text: 'The workout ends. The change keeps working.', kind: 'wise', author: null },
  { text: 'Every finished session is evidence you can keep going.', kind: 'wise', author: null },
  // --- Claude ---
  { text: 'Look at you. You said you would, and you did.', kind: 'hype', author: null },
  { text: 'That right there is what commitment looks like.', kind: 'hype', author: null },
  { text: 'You showed up tired and left stronger. That\'s the deal.', kind: 'hype', author: null },
  { text: 'I am so proud of you. Every single rep counted.', kind: 'hype', author: null },
  { text: 'Done. Logged. Cannot be taken from you. That\'s yours.', kind: 'hype', author: null },
  { text: 'Not everyone does what you just did. Remember that.', kind: 'hype', author: null },
  { text: 'The version of you who skipped? Doesn\'t exist today.', kind: 'hype', author: null },
  { text: 'You earned the rest now. Go enjoy it fully.', kind: 'hype', author: null },
  { text: 'We said we\'d do it. We did it. That\'s who we are.', kind: 'hype', author: null },
  { text: 'Streak intact. Heart full. Body earned. Let\'s go.', kind: 'hype', author: null },
  { text: 'Take your victories, cherish them, use them, but don\'t settle for them.', kind: 'wise', author: 'Mia Hamm' },
  { text: 'Failure happens every day in practice. What makes you better is how you react.', kind: 'wise', author: 'Mia Hamm' },
  { text: 'Champions aren\'t made in gyms. They\'re made from something deep inside.', kind: 'wise', author: 'Muhammad Ali' },
  { text: 'It is not one swallow or one fine day that makes a spring.', kind: 'wise', author: 'Aristotle' },
  { text: 'The work you did today will be silent until it speaks loudly.', kind: 'wise', author: null },
  { text: 'Effort compounds quietly. You just made a deposit.', kind: 'wise', author: null },
  { text: 'The gap between who you were and who you\'re becoming closes rep by rep.', kind: 'wise', author: null },
  { text: 'Rest belongs to those who earned it. You earned it.', kind: 'wise', author: null },
  { text: 'One session is a day. A hundred sessions is a life.', kind: 'wise', author: null },
  { text: 'You don\'t always feel progress. But it\'s always there, accumulating.', kind: 'wise', author: null },
  // --- Gemini ---
  { text: 'Look at that, you absolutely dominated today.', kind: 'hype', author: null },
  { text: 'You showed up, you worked, and you won. Proud of you.', kind: 'hype', author: null },
  { text: 'That intensity was exactly what you needed. Great job.', kind: 'hype', author: null },
  { text: 'Feeling good? You earned every bit of this glow.', kind: 'hype', author: null },
  { text: 'You didn\'t just log a workout, you proved your drive.', kind: 'hype', author: null },
  { text: 'Hard work looks good on you. Keep that momentum.', kind: 'hype', author: null },
  { text: 'Take a breath, you left it all on the floor today.', kind: 'hype', author: null },
  { text: 'Unstoppable. Another notch on the belt, my friend.', kind: 'hype', author: null },
  { text: 'You did it. That discipline is changing everything.', kind: 'hype', author: null },
  { text: 'Take a moment to soak in that well-earned pride.', kind: 'hype', author: null },
  { text: 'What we achieve inwardly will change outer reality.', kind: 'wise', author: 'Plutarch' },
  { text: 'The soreness you feel today is strength tomorrow.', kind: 'wise', author: null },
  { text: 'Consistency is what transforms average into excellence.', kind: 'wise', author: null },
  { text: 'We are what we repeatedly do.', kind: 'wise', author: 'Will Durant' },
  { text: 'Trust the work, the results will follow in time.', kind: 'wise', author: null },
  { text: 'Victory is in the quality of the effort, not the weight.', kind: 'wise', author: null },
  { text: 'The finish line is just the start of the next goal.', kind: 'wise', author: null },
  { text: 'Your future self will thank you for this today.', kind: 'wise', author: null },
  { text: 'Strength grows in the moments when you keep going.', kind: 'wise', author: null },
  { text: 'Respect your body enough to give it your best.', kind: 'wise', author: null },
  // --- DeepSeek ---
  { text: 'That was all you — and you delivered. Proud of you.', kind: 'hype', author: null },
  { text: 'The only limit to our realization of tomorrow is our doubts of today.', kind: 'wise', author: 'Franklin D. Roosevelt' },
  { text: 'You crushed it — that feeling is your reward.', kind: 'hype', author: null },
  { text: 'It does not matter how slowly you go as long as you do not stop.', kind: 'wise', author: 'Confucius' },
  { text: 'Look at you — just showed up and gave it everything.', kind: 'hype', author: null },
  { text: 'Effort is between you and yourself — and you won today.', kind: 'wise', author: null },
  { text: 'That one\'s in the books — and you\'re tougher for it.', kind: 'hype', author: null },
  { text: 'Believe you can and you\'re halfway there.', kind: 'wise', author: 'Theodore Roosevelt' },
  { text: 'You\'re not the same person who started — that\'s the win.', kind: 'hype', author: null },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', kind: 'wise', author: 'Winston Churchill' },
  { text: 'Celebrate this — you just leveled up.', kind: 'hype', author: null },
  { text: 'The best time to start was yesterday — the next best is now.', kind: 'wise', author: null },
  { text: 'You earned every second of that pride — soak it in.', kind: 'hype', author: null },
  { text: 'Do not let what you cannot do interfere with what you can do.', kind: 'wise', author: 'John Wooden' },
  { text: 'That was a statement — to yourself and the world.', kind: 'hype', author: null },
  { text: 'Champions are made from something deep inside — a will, a dream, a vision.', kind: 'wise', author: 'Muhammad Ali' },
  { text: 'You just did what you came to do — respect.', kind: 'hype', author: null },
  { text: 'Small daily improvements over time lead to stunning results.', kind: 'wise', author: 'Robin Sharma' },
  { text: 'That sweat is your trophy — wear it with pride.', kind: 'hype', author: null },
  { text: 'What you get by achieving your goals is not as important as what you become.', kind: 'wise', author: 'Zig Ziglar' },
]
